In [8]:
import pandas as pd
from loguru import logger

# Set pandas columns width to 100
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_columns', 100)

In [30]:
# Read file at Time_to_death_modelling/data/interim/base_df.csv
df = pd.read_csv("../data/interim/cohort_df.csv")
df.head(30)

,subject_id,hadm_id,admittime,dischtime,age,gender,race,insurance,label,dod,time_to_death,los,admission_type,admission_location,discharge_location
0,10001884,21268656,2125-10-18 16:50:00,2125-10-20 15:15:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1919.298611,1,EW EMER.,EMERGENCY ROOM,HOME
1,10001884,26679629,2125-10-26 20:32:00,2125-10-27 16:28:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1911.144444,0,EW EMER.,EMERGENCY ROOM,HOME
2,10001884,23594368,2125-11-30 16:02:00,2125-12-03 14:44:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1876.331944,2,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
3,10001884,21577720,2125-12-26 17:06:00,2125-12-27 16:52:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1850.287500,0,EU OBSERVATION,EMERGENCY ROOM,0
4,10001884,24325811,2126-11-04 00:50:00,2126-11-04 12:49:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1537.965278,0,EU OBSERVATION,EMERGENCY ROOM,0
5,10001884,26812645,2127-07-24 18:06:00,2127-07-25 17:41:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1275.245833,0,EU OBSERVATION,EMERGENCY ROOM,0
6,10001884,27765344,2127-12-11 18:06:00,2127-12-12 13:46:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,1135.245833,0,DIRECT OBSERVATION,PHYSICIAN REFERRAL,0
7,10001884,25758848,2128-07-15 18:44:00,2128-07-17 13:31:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,918.219444,1,EU OBSERVATION,EMERGENCY ROOM,0
8,10001884,29675586,2130-04-08 22:06:00,2130-04-09 14:30:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,286.079167,0,EU OBSERVATION,EMERGENCY ROOM,0
9,10001884,26170293,2130-04-15 21:10:00,2130-04-19 16:00:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,279.118056,3,EW EMER.,EMERGENCY ROOM,HOME
10,10001884,27016754,2130-06-23 22:14:00,2130-06-24 11:07:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,210.073611,0,EU OBSERVATION,EMERGENCY ROOM,0
11,10001884,26202981,2130-08-21 15:26:00,2130-08-23 16:40:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,151.356944,2,EW EMER.,EMERGENCY ROOM,HOME
12,10001884,21192799,2130-10-05 20:04:00,2130-10-06 15:05:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,106.163889,0,EU OBSERVATION,EMERGENCY ROOM,0
13,10001884,29678536,2130-10-08 19:03:00,2130-10-12 19:05:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,103.206250,4,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
14,10001884,22532141,2130-10-14 00:58:00,2130-10-14 13:57:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,97.959722,0,EU OBSERVATION,EMERGENCY ROOM,0
15,10001884,28475784,2130-10-19 16:20:00,2130-10-22 15:13:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,92.319444,2,EW EMER.,EMERGENCY ROOM,SKILLED NURSING FACILITY
16,10001884,28669374,2130-11-19 18:35:00,2130-11-20 10:46:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,61.225694,0,EU OBSERVATION,EMERGENCY ROOM,0
17,10001884,28664981,2130-11-28 16:47:00,2130-11-30 15:34:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,52.300694,1,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
18,10001884,24962904,2130-12-06 20:14:00,2130-12-08 18:00:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,44.156944,1,EW EMER.,EMERGENCY ROOM,SKILLED NURSING FACILITY
19,10001884,27507515,2130-12-23 19:32:00,2130-12-24 16:42:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,27.186111,0,EU OBSERVATION,EMERGENCY ROOM,0
20,10001884,24746267,2130-12-27 21:23:00,2130-12-30 15:33:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,0,2131-01-20 00:00:00,23.109028,2,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
21,10001884,26184834,2131-01-07 20:39:00,2131-01-20 05:15:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,1,2131-01-20 00:00:00,12.139583,12,OBSERVATION ADMIT,EMERGENCY ROOM,DIED
22,10002155,28439444,2128-07-29 17:01:00,2128-07-31 18:00:00,80,F,WHITE,Other,0,2131-03-10 00:00:00,953.290972,2,EW EMER.,EMERGENCY ROOM,HOME
23,10002155,23822395,2129-08-04 12:44:00,2129-08-18 16:53:00,80,F,WHITE,Other,0,2131-03-10 00:00:00,582.469444,14,EW EMER.,PROCEDURE SITE,CHRONIC/LONG TERM ACUTE CARE
24,10002155,28976727,2129-12-24 01:36:00,2129-12-25 19:18:00,80,F,WHITE,Other,0,2131-03-10 00:00:00,440.933333,1,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
25,10002155,28994087,2130-09-23 21:59:00,2130-09-29 18:55:00,80,F,WHITE,Other,0,2131-03-10 00:00:00,167.084028,5,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
26,10002155,20345487,2131-03-09 20:33:00,2131-03-10 01:55:00,80,F,WHITE,Other,1,2131-03-10 00:00:00,0.143750,0,EW EMER.,EMERGENCY ROOM,DIED
27,10003400,26090619,2134-06-06 02:25:00,2134-06-07 15:05:00,72,F,BLACK/AFRICAN AMERICAN,Medicare,0,2137-09-02 00:00:00,1183.899306,1,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE
28,10003400,29483621,2136-11-04 20:43:00,2136-11-12 17:40:00,72,F,BLACK/AFRICAN AMERICAN,Medicare,0,2137-09-02 00:00:00,301.136806,7,EW EMER.,EMERGENCY ROOM,SKILLED NURSING FACILITY
29,10003400,26467376,2136-12-09 14:44:00,2136-12-15 16:00:00,72,F,BLACK/AFRICAN AMERICAN,Medicare,0,2137-09-02 00:00:00,266.386111,6,EW EMER.,EMERGENCY ROOM,SKILLED NURSING FACILITY

In [24]:
df.shape

(31043, 15)

In [25]:
# Check value counts of the label
df['label'].value_counts()

label
0    22727
1     8316
Name: count, dtype: int64

In [29]:
# Read file at Time_to_death_modelling/data/interim/base_df.csv
df = pd.read_csv("../data/interim/time_to_death_df.csv")
df.head(30)

,subject_id,hadm_id,admittime,dischtime,age,gender,race,insurance,label,dod,time_to_death,los,admission_type,admission_location,discharge_location
0,10001884,26184834,2131-01-07 20:39:00,2131-01-20 05:15:00,68,F,BLACK/AFRICAN AMERICAN,Medicare,1,2131-01-20 00:00:00,12.139583,12,OBSERVATION ADMIT,EMERGENCY ROOM,DIED
1,10002155,20345487,2131-03-09 20:33:00,2131-03-10 01:55:00,80,F,WHITE,Other,1,2131-03-10 00:00:00,0.143750,0,EW EMER.,EMERGENCY ROOM,DIED
2,10003400,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,72,F,BLACK/AFRICAN AMERICAN,Medicare,1,2137-09-02 00:00:00,28.995139,29,URGENT,TRANSFER FROM HOSPITAL,DIED
3,10004401,25777141,2144-06-05 19:45:00,2144-06-18 21:30:00,82,M,WHITE,Medicare,1,2144-06-18 00:00:00,12.177083,13,EW EMER.,EMERGENCY ROOM,DIED
4,10004720,22081550,2186-11-12 18:01:00,2186-11-17 18:30:00,61,M,WHITE,Medicare,1,2186-11-17 00:00:00,4.249306,5,EW EMER.,INFORMATION NOT AVAILABLE,DIED
5,10005024,25023471,2138-03-29 01:17:00,2138-04-19 11:30:00,60,M,UNKNOWN,Medicaid,1,2138-04-19 00:00:00,20.946528,21,EW EMER.,EMERGENCY ROOM,DIED
6,10005817,28661809,2135-01-03 21:54:00,2135-01-19 18:36:00,66,M,WHITE,Medicare,1,2135-01-19 00:00:00,15.087500,15,OBSERVATION ADMIT,TRANSFER FROM HOSPITAL,DIED
7,10006053,22942076,2111-11-13 23:39:00,2111-11-15 17:20:00,52,M,UNKNOWN,Medicaid,1,2111-11-15 00:00:00,1.014583,1,URGENT,TRANSFER FROM HOSPITAL,DIED
8,10007818,22987108,2146-06-10 16:37:00,2146-07-12 00:00:00,69,M,WHITE,Medicare,1,2146-07-12 00:00:00,31.307639,31,DIRECT EMER.,PHYSICIAN REFERRAL,DIED
9,10010058,26359957,2147-11-18 02:34:00,2147-11-19 04:00:00,80,M,ASIAN - SOUTH EAST ASIAN,Other,1,2147-11-19 00:00:00,0.893056,1,EW EMER.,PHYSICIAN REFERRAL,DIED
10,10010471,29842315,2155-12-02 19:36:00,2155-12-07 15:30:00,89,F,WHITE,Medicare,1,2155-12-07 00:00:00,4.183333,4,EW EMER.,EMERGENCY ROOM,DIED
11,10010795,27301109,2174-05-27 19:28:00,2174-05-28 20:00:00,44,M,WHITE,Other,1,2174-05-28 00:00:00,0.188889,1,URGENT,TRANSFER FROM HOSPITAL,HOME
12,10011365,26712576,2166-02-11 14:09:00,2166-02-20 00:20:00,73,F,WHITE,Medicare,1,2166-02-20 00:00:00,8.410417,8,EW EMER.,EMERGENCY ROOM,DIED
13,10011849,20188892,2185-08-28 20:27:00,2185-10-09 11:38:00,64,F,HISPANIC/LATINO - CENTRAL AMERICAN,Other,1,2185-10-09 00:00:00,41.147917,41,EW EMER.,WALK-IN/SELF REFERRAL,DIED
14,10012292,28665904,2171-07-17 18:43:00,2171-07-21 00:00:00,69,F,WHITE,Medicare,1,2171-07-21 00:00:00,3.220139,3,EW EMER.,EMERGENCY ROOM,DIED
15,10015931,22130791,2177-03-24 21:47:00,2177-03-29 14:15:00,87,M,WHITE,Medicare,1,2177-03-29 00:00:00,4.092361,4,URGENT,TRANSFER FROM HOSPITAL,DIED
16,10017492,27417763,2116-06-26 18:25:00,2116-07-05 08:05:00,84,M,PATIENT DECLINED TO ANSWER,Medicaid,1,2116-07-05 00:00:00,8.232639,8,EW EMER.,EMERGENCY ROOM,DIED
17,10017851,29414705,2115-11-21 18:14:00,2115-11-23 01:00:00,75,M,WHITE,Medicare,1,2115-11-23 00:00:00,1.240278,1,EW EMER.,EMERGENCY ROOM,DIED
18,10021927,24623461,2180-09-20 10:01:00,2180-09-27 10:32:00,65,F,WHITE,Medicare,1,2180-09-27 00:00:00,6.582639,7,EW EMER.,EMERGENCY ROOM,DIED
19,10023117,21607814,2175-07-06 15:57:00,2175-07-20 00:00:00,53,M,WHITE,Medicare,1,2175-07-20 00:00:00,13.335417,13,OBSERVATION ADMIT,EMERGENCY ROOM,DIED
20,10024982,25154057,2203-09-19 12:29:00,2203-10-11 19:10:00,78,M,WHITE,Medicare,1,2203-10-11 00:00:00,21.479861,22,EW EMER.,EMERGENCY ROOM,DIED
21,10025463,24470193,2137-10-08 21:20:00,2137-10-09 15:30:00,66,M,WHITE,Other,1,2137-10-09 00:00:00,0.111111,0,EW EMER.,EMERGENCY ROOM,DIED
22,10026161,24614671,2133-11-11 07:15:00,2133-11-15 18:05:00,78,M,WHITE,Medicare,1,2133-11-15 00:00:00,3.697917,4,SURGICAL SAME DAY ADMISSION,PHYSICIAN REFERRAL,DIED
23,10026255,22059910,2201-07-07 18:15:00,2201-07-13 23:27:00,66,M,WHITE,Other,1,2201-07-13 00:00:00,5.239583,6,EW EMER.,EMERGENCY ROOM,DIED
24,10026868,23527884,2149-11-09 20:06:00,2149-11-13 16:30:00,86,M,WHITE,Medicare,1,2149-11-13 00:00:00,3.162500,3,EW EMER.,EMERGENCY ROOM,DIED
25,10026879,29403608,2159-04-09 17:06:00,2159-04-20 10:11:00,84,M,WHITE,Other,1,2159-04-20 00:00:00,10.287500,10,OBSERVATION ADMIT,PHYSICIAN REFERRAL,DIED
26,10032409,28020206,2133-09-16 18:07:00,2133-10-01 12:30:00,73,F,BLACK/AFRICAN AMERICAN,Medicare,1,2133-10-01 00:00:00,14.245139,14,EW EMER.,EMERGENCY ROOM,HOME
27,10035168,26166196,2146-12-22 17:46:00,2147-01-07 08:30:00,56,F,WHITE,Medicare,1,2147-01-07 00:00:00,15.259722,15,DIRECT EMER.,PHYSICIAN REFERRAL,DIED
28,10035631,29276678,2116-02-27 20:55:00,2116-03-12 07:45:00,63,M,WHITE,Other,1,2116-03-12 00:00:00,13.128472,13,OBSERVATION ADMIT,EMERGENCY ROOM,DIED
29,10037861,24540843,2117-03-14 16:34:00,2117-03-24 00:01:00,77,M,UNKNOWN,Medicare,1,2117-03-24 00:00:00,9.309722,9,EW EMER.,EMERGENCY ROOM,DIED

In [31]:
# Read file at Time_to_death_modelling/data/interim/base_df.csv
df = pd.read_csv("../data/interim/diagnosis_feat_df.csv")
df.head(30)

,subject_id,hadm_id,count_prior_admissions,count_unique_diagnoses_prior,avg_diagnoses_per_prior_admission,time_since_last_admission_days,admission_frequency_last_year,flag_history_CHF_ICD_CODES,flag_history_DIABETES_ICD_CODES,flag_history_CKD_ICD_CODES,count_prior_admissions_with_CHF_ICD_CODES,time_since_first_diagnosis_CHF_ICD_CODES_years,count_prior_admissions_with_DIABETES_ICD_CODES,time_since_first_diagnosis_DIABETES_ICD_CODES_years,count_prior_admissions_with_CKD_ICD_CODES,time_since_first_diagnosis_CKD_ICD_CODES_years
0,10001884,26184834,21,80,10.428571,8,13,0,0,0,0,NaN,0,NaN,0,NaN
1,10002155,20345487,4,41,13.500000,161,1,1,0,1,2,1.59,0,NaN,2,1.59
2,10003400,23559586,6,75,19.166667,137,5,1,0,1,2,0.65,0,NaN,5,0.75
3,10004401,25777141,11,99,21.090909,13,7,1,0,1,11,3.00,0,NaN,3,1.77
4,10005817,28661809,1,26,26.000000,744,0,1,1,0,1,2.06,1,2.06,0,NaN
5,10010058,26359957,4,45,14.250000,315,1,1,0,1,4,8.39,0,NaN,4,8.39
6,10010471,29842315,1,16,16.000000,206,1,0,0,1,0,NaN,0,NaN,1,0.57
7,10010795,27301109,1,6,6.000000,88,1,0,0,0,0,NaN,0,NaN,0,NaN
8,10011365,26712576,4,40,12.000000,14,1,0,0,0,0,NaN,0,NaN,0,NaN
9,10012292,28665904,4,41,16.500000,45,2,0,0,0,0,NaN,0,NaN,0,NaN
10,10015931,22130791,2,49,28.500000,83,2,1,0,1,2,0.36,0,NaN,2,0.36
11,10017492,27417763,1,9,9.000000,815,0,0,0,0,0,NaN,0,NaN,0,NaN
12,10017851,29414705,1,7,7.000000,15,1,1,0,0,1,0.05,0,NaN,0,NaN
13,10021927,24623461,11,98,15.181818,12,3,1,0,0,2,1.67,0,NaN,0,NaN
14,10023117,21607814,6,85,19.666667,98,2,1,0,1,5,4.75,0,NaN,5,3.66
15,10024982,25154057,4,37,12.250000,0,2,1,0,1,1,0.83,0,NaN,1,0.83
16,10025463,24470193,1,5,5.000000,340,1,0,0,0,0,NaN,0,NaN,0,NaN
17,10026161,24614671,1,5,5.000000,30,1,0,0,0,0,NaN,0,NaN,0,NaN
18,10026255,22059910,1,13,13.000000,280,1,0,0,0,0,NaN,0,NaN,0,NaN
19,10026868,23527884,1,16,16.000000,7,1,0,1,0,0,NaN,1,0.04,0,NaN
20,10032409,28020206,14,72,13.785714,238,1,1,1,0,2,4.30,14,7.05,0,NaN
21,10035168,26166196,10,60,11.100000,3,5,1,0,0,1,0.99,0,NaN,0,NaN
22,10035631,29276678,8,76,12.500000,12,2,0,0,0,0,NaN,0,NaN,0,NaN
23,10037861,24540843,1,25,25.000000,512,0,1,1,1,1,1.43,1,1.43,1,1.43
24,10038688,25926997,4,23,6.750000,1952,0,0,0,0,0,NaN,0,NaN,0,NaN
25,10041127,23095285,3,14,6.333333,16,3,0,0,0,0,NaN,0,NaN,0,NaN
26,10047172,21396386,4,55,17.500000,15,4,0,1,0,0,NaN,1,0.87,0,NaN
27,10050755,20050796,3,37,14.333333,9,2,0,0,0,0,NaN,0,NaN,0,NaN
28,10053082,24211160,1,7,7.000000,25,1,0,0,0,0,NaN,0,NaN,0,NaN
29,10055344,29209451,5,24,8.400000,1026,0,1,1,0,4,4.82,3,3.50,0,NaN

In [32]:
df.columns

Index(['subject_id', 'hadm_id', 'count_prior_admissions',
       'count_unique_diagnoses_prior', 'avg_diagnoses_per_prior_admission',
       'time_since_last_admission_days', 'admission_frequency_last_year',
       'flag_history_CHF_ICD_CODES', 'flag_history_DIABETES_ICD_CODES',
       'flag_history_CKD_ICD_CODES',
       'count_prior_admissions_with_CHF_ICD_CODES',
       'time_since_first_diagnosis_CHF_ICD_CODES_years',
       'count_prior_admissions_with_DIABETES_ICD_CODES',
       'time_since_first_diagnosis_DIABETES_ICD_CODES_years',
       'count_prior_admissions_with_CKD_ICD_CODES',
       'time_since_first_diagnosis_CKD_ICD_CODES_years'],
      dtype='object')